### ISSUE TITLE
0 songs loaded, starting

### ISSUE THREAD

**Issue by TheTou** [Repulser/Moosic#12]
I have youtube URLs in songs.txt, when I start the bot I get the message "Found a playlist, parsing" multiple times and then at the end the following:

```
...
Found a playlist, parsing
Found a playlist, parsing
0 songs loaded, starting
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at co.moosic.music.TrackScheduler.getRandomSong(TrackScheduler.java:114)
        at co.moosic.music.TrackScheduler.nextTrack(TrackScheduler.java:147)
        at co.moosic.music.TrackScheduler.<init>(TrackScheduler.java:46)
        at co.moosic.music.Login.main(Login.java:58)

```

The bot joined the voice channel but no song is playing

**Comment by Repulser** [comment]
Can you include your songs.txt?

**Comment by TheTou** [comment]
[songs.txt](https://github.com/Repulser/Moosic/files/1688720/songs.txt)

Sure, here you go

**Comment by Repulser** [comment]
It seems that your'e using /v/ links which are not supported, i have compiled an updated songs.txt for you, please let me know if it works
[songs.txt](https://github.com/Repulser/Moosic/files/1688735/songs.txt)

**Comment by TheTou** [comment]
Good to know! Now it works perfectly, thank you so much for the fast help :)

**Comment by Repulser** [comment]
Glad it works, enjoy!
