### ISSUE TITLE
Bot logs into server and says "Playing" but no audio in the channel

### ISSUE THREAD

**Issue by bvislocky** [Repulser/Moosic#31]
[ ERROR] [LocalAudioTrackExecutor] Error in playback of doFnCzUxLU8
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:79)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:108)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:97)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:140)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:156)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:77)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 common frames omitted

**Comment by bvislocky** [comment]
Apparently it works fine with soundcloud. It's the youtube link that had an issue

**Comment by BrendonTmg** [comment]
I'm getting this same issue, does it happen with every youtube link?

**Comment by bvislocky** [comment]
I've only tried a handful of youtube links, but it seemed to happen with every one I tried

**Comment by LubricantJam** [comment]
Same thing here, I'd assume this has been abandoned and we'd need to find someone that has an updated fork.

**Comment by LubricantJam** [comment]
@Repulser Any ideas?

**Comment by Repulser** [comment]
Lavaplayer needs to be updated, I might look into it soon, If you want to help me test things feel free to send me a direct message on Discord by joining my server at https://discordapp.com/invite/cf3tNMW and messaging me (ImBursting#0051)

**Comment by Repulser** [comment]
Hey, please check out this release https://github.com/Repulser/Moosic/releases/tag/5.2 with a fixed version

**Comment by Repulser** [comment]
Also pinging @LubricantJam

**Comment by bvislocky** [comment]
Downloaded the fixed release and now it runs youtube links just fine. 
I added one youtube song and ran the bot and it loaded without any issue.
Thanks a ton for the fix!
