### ISSUE TITLE
Bot cant load youtube link

### ISSUE THREAD

**Issue by d4rkr4g3** [Repulser/Moosic#32]
Hi all,
i have the following problem:
- I am using a Raspberry Pi 3 with Raspbian Stretch and installed OpenJDK 9.
- I downloaded the files bot.cfg, moosic.jar, run_linux.sh and songs.txt and put them in a folder "moosic" in home.
- i edited the songs.txt to just one test song on youtube
- I created a discord bot, edited bot.cfg for the token and the voice-channel id, invited it and finally gave the bot connect and speech permission for the voice-channel
- i chmod+x the run_linux.sh and started it

Now i receive the following output:

`pi@Argus:~/moosic $ sudo ./run_linux.sh
[ INFO ] [Reflections] Reflections took 592 ms to scan 1 urls, producing 1 keys and 5 values
[ INFO ] [Reflections] Reflections took 5643 ms to scan 1 urls, producing 1962 keys and 10172 values
[ INFO ] [JDA] Login Successful!
[ INFO ] [WebSocketClient] Connected to WebSocket
[ INFO ] [JDA] Finished Loading!
Use this url to add me:
https://discordapp.com/oauth2/authorize?client_id=xxxxxxxxxxxxxxxxxx&scope=bot
Created new player manager
[ INFO ] [AudioManager] Audio System successfully setup!
Joined designated voice channel metal-radio
Processing 1 songs
1 songs loaded, starting
[ ERROR] [DefaultAudioPlayerManager] Error in loading item https://www.youtube.com/watch?v=pKHRerwGXwU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:209)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrack(YoutubeAudioSourceManager.java:246)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:177)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:121)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:429)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:415)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:219)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException: null
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:205)
        ... 10 common frames omitted
`

In discord i can see that the moosic-bot is connected to the channel but doesnt play the music. I also tried to use other songs but the result remains the same.

Did i miss something?

Thanks for any kind of help or advice

**Comment by Repulser** [comment]
Hey, please check out this release with a fixed version https://github.com/Repulser/Moosic/releases/tag/5.2
